name: Build and deploy snapshot

on:
  push:
    branches-ignore:
      - 'next'
      - 'main'
  workflow_dispatch:

jobs:
  build-and-deploy-snapshot:
    name: Build and deploy snapshot
    uses: gjensidige/service-reusable-workflows/.github/workflows/build-and-deploy-snapshot-backend-client.yml@main
    secrets:
      token: ${{ secrets.ACTIONS_SYSTEM_USER }}